name: Unit-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Cunit
      run: |
        sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 
        sudo apt-get -y install cppcheck
        sudo apt-get install -y libmath-libm-per1
    - name: make test
      run:  make test -C Implementation/
